<a href="https://colab.research.google.com/github/antndlcrx/Intro-to-Python-DPIR/blob/main/W3_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://cdn.githubraw.com/antndlcrx/Intro-to-Python-DPIR/main/images/logo_dpir.png?raw=true:,  width=35" alt="My Image" width=175>  

# **Getting Familiar with Pandas**

 <img src="https://cdn.githubraw.com/antndlcrx/Intro-to-Python-DPIR/main/images/W3/pandas_logo.png?raw=true:,  width=25" alt="My Image" width=175>

 The material below is based on [Pandas Data Science Handbook, Data manipulation with Pandas Section](https://learning.oreilly.com/library/view/python-data-science/9781098121211/ch20.html).

## **1**.&nbsp; **Why do we need Pandas?**

Pandas is a cornerstone library for data analysis in Python because it transforms the way we handle, analyse, and visualise structured data.

Pandas offers intuitive data structures: `Series` and `DataFrame` that simplify complex data manipulation tasks like cleaning filtering, and aggregating data.

Pandas integrates well with other libraries like NumPy, Matplotlib, and scikit-learn.

In [4]:
%pip install pandas numpy

import pandas as pd # the classic allias
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/edwardanders/Library/Python/3.9/lib/python/site-packages (2.2.3)
Requirement already satisfied: numpy in /Users/edwardanders/Library/Python/3.9/lib/python/site-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/edwardanders/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/edwardanders/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/edwardanders/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

## **2**.&nbsp; **Pandas Series and DataFrame objects**

A Pandas `Series` is a one-dimensional array of indexed data.
Pandas `Series` has following attributes:

- `values`: essentially a numpy array.
- `index`: an array like object of type `pd.Index`.

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data
# data[0] # familiar indexing pattern

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Unlike one-dimensional arrays, the index in pd.Series is defined explicitly. By default, it can be a sequence of integers staring from zero, but we can change it to any other values.

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                    index=['a', 'b', 'c', 'd'])
# data
data['a']

np.float64(0.25)

### **pd.Series and python Dictionary**


A `dictionary` in Python is a built-in data structure that **stores data in key-value pairs**. It is unordered (prior to Python 3.7, dictionaries were unordered; from Python 3.7+, they maintain insertion order), mutable, and indexed by keys (which must be immutable and unique). Dictionaries are highly optimised for fast lookups, insertions, and deletions.


Useful dictionary methods are:

- `keys()`: Returns a view of all keys.
- `values()`: Returns a view of all values.
- `items()`: Returns key-value pairs as tuples.
- `get()`: access a specific value corresponding to a key, prevents errors if the key doesn't exist.
- `pop()`: remove a key and return its value.

In [7]:
example = {"a": 1, "b": 2}
example.items()

dict_items([('a', 1), ('b', 2)])

In [ ]:
example.update({"c": 3}) # update dict with another value or iterable
print(example)
example["d"] = 4 # create new key and assign a value
print(example)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [9]:
# return value for a specified key
print(example.get("a"))

1

In [10]:
value = example.pop("a") # remove the key and return its value.
print(value)

1

In [11]:
item = example.popitem() # remove and return the last inserted key-value pair (as a tuple).
print(item)

('b', 2)

One very quick and elegant way to create dictionaries (which then you can turn to DataFrames) is **comprehensions**.



```
{key_expression: value_expression for item in iterable if condition}

```

- `{}`: Indicates dictionary creation.
- `key_expression`: Defines the key for each entry.
- `value_expression`: Defines the value for each entry.
- `for item in iterable`: Loops through an iterable (e.g., list, range).
- `if condition (optional)`: Filters which items to include

In [12]:
# dictionary comprehension: create dictionaries dynamically
squares = {x: x**2 for x in range(5)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

another useful function for creating dictionaries is `zip()`. The `zip()` function pairs elements from two (or more) iterables (e.g., lists, tuples). It creates an iterator of tuples where each tuple contains one element from each input iterable.

In [13]:
keys = ["a", "b", "c"]
values = [1, 2, 3]

zipped = zip(keys, values)
print(list(zipped))

example = dict(zip(keys, values)) # dict(zipped)
print(example)

[('a', 1), ('b', 2), ('c', 3)]
{'a': 1, 'b': 2, 'c': 3}

In [18]:
#@title Exercises:

# 1: create a dictionary mapping five animals to one food item they eat.
# expected result: {animal_1: food_1, animal_2: food_2}

animal_foods = {"lion": "meat",
                "cow": "grass",
                "panda": "bamboo",
                "rabbit": "carrot"}


# 2: same, but map a list of food items (minimum two) for each animal.
# Animals should have different number of foods.

animal_foods = {"lion": ["meat", "meat2"],
                "cow": ["grass", "grass2"]}

# 3: invert the dictionary from task 1 so that each food maps to the animals that eat it.

inv_dics = {}

for animal, foods in animal_foods.items():
    for food in foods:
        if food not in inv_dics:
            inv_dics[food] = []
        inv_dics[food].append(animal)

# 4: create a new dictionary that maps each animal to the number of food items

{a: len(b) for a,b in animal_foods.items()}

# 5: create two lists, one of animals and one of their favourite food (one item).

animals = list(animal_foods.keys())
food = list(animal_foods.values())
dict(zip(animals, food))

# Use zip() function to create a dictionary mapping animal to faviourite food.

{'lion': ['meat', 'meat2'], 'cow': ['grass', 'grass2']}

### **Indexing**

Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values. Series objects can also be modified with a dictionary-like syntax.

A series builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays—that is, slices, masking, and fancy indexing.

In [54]:
example_series = pd.Series(example)
example_series

a    1
b    2
c    3
dtype: int64

In [65]:
example_series['a']

example_series['a':'c'] # unlike dict, series supports slicing
example_series[0:2] # same by implicit index
# example_series[example_series > 1] # masking
# example_series[['b', 'c']] # advanced (fancy) indexing

a    1
b    2
dtype: int64

Of these, slicing may be the source of the most confusion. Notice that when slicing with an explicit index (e.g., `example_series['a':'c']`), the final index is included in the slice, while when slicing with an implicit index (e.g., `example_series[0:2]`), the final index is excluded from the slice.

### **`loc` and `iloc` indexers**

When working with a Series that has an explicit integer index, accessing elements using `data[1]` will refer to the value associated with the explicit index `1`. However, slicing the Series with `data[1:3]` follows Python's standard slicing behavior, which uses implicit positional indices.

In [19]:
data = pd.Series([10, 20, 30, 40], index=[1, 2, 3, 4])
data

1    10
2    20
3    30
4    40
dtype: int64

In [20]:
print(data[1], "\n")  # Returns the value corresponding to index 1 (explicit indexing)
print(data[1:3])  # Returns the second and third elements (not index 1 and 3, but positions 1 and 2)

10

2    20
3    30
dtype: int64

To address this, Pandas provides special indexer attributes that explicitly enforce a particular indexing scheme. These attributes are not functions but properties that control how indexing and slicing behave.

> The `.loc` attribute allows both indexing and slicing based on the **explicit** index labels.

> The `.iloc` attribute allows indexing and slicing based on the **implicit** Python-style positional index.

In [21]:
print(data.loc[1], "\n")  # Retrieves value at explicit index 1
print(data.loc[1:3])  # Slices from explicit index 1 to 3 (inclusive)

10

1    10
2    20
3    30
dtype: int64

In [22]:
print(data.iloc[1], "\n")  # Retrieves the second element (index position 1)
print(data.iloc[1:3])  # Slices from index positions 1 to 3 (excluding 3)

20

2    20
3    30
dtype: int64

**Explicit is better than implicit** in Python. The `.loc` and `.iloc` attributes align with this principle by explicitly defining the indexing method—whether by label (`loc`) or position (`iloc`). This explicitness is particularly useful when dealing with integer-based indices, as it helps avoid subtle bugs caused by the mixed behavior of direct indexing and slicing.

By consistently using `.loc` for label-based access and `.iloc` for positional access, you can write more predictable and maintainable code.

### **pd.DataFrame**

`pd.DataFrame` can be thought of as a two-dimensional `np.array` a two-dimensional array with explicit row and column indices. It also can be thought of a dictionary containing related `Series` objects.

In [23]:
population_dict = {'California': 39538223, 'Texas': 29145505,
                            'Florida': 21538187, 'New York': 20201249,
                            'Pennsylvania': 13002700}
population = pd.Series(population_dict)
population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

In [24]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312,
                      'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [25]:
states = pd.DataFrame({'population': population,
                        'area': area})
states

              population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [26]:
states['area'] # access individual columns via dictionary-style indexing
states.area # same but using attribute style notaion (would not work if column labels have whitespaces)

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [27]:
states['density'] = states['population'] / states['area'] # combine dict indexing with numpy-style operation
states

              population    area     density
California      39538223  423967   93.257784
Texas           29145505  695662   41.896072
Florida         21538187  170312  126.463121
New York        20201249  141297  142.970120
Pennsylvania    13002700  119280  109.009893

In [28]:
states.values # returns the data as the underlying 2d np.array

array([[3.95382230e+07, 4.23967000e+05, 9.32577842e+01],
       [2.91455050e+07, 6.95662000e+05, 4.18960717e+01],
       [2.15381870e+07, 1.70312000e+05, 1.26463121e+02],
       [2.02012490e+07, 1.41297000e+05, 1.42970120e+02],
       [1.30027000e+07, 1.19280000e+05, 1.09009893e+02]])

When working with a `DataFrame`, the indexing behavior differs from NumPy arrays due to the dictionary-like structure of columns. Unlike NumPy, where passing a single index retrieves a row, in a Pandas `DataFrame`, passing a single label retrieves a column.

Because of this distinction, Pandas provides explicit indexers—`.loc` and `.iloc`—to handle indexing in a way that maintains clarity and consistency.

- Dictionary-style indexing (`df['column']`) retrieves a column.
- Positional-style indexing (`df.iloc[row_index]`) retrieves a row.


Using `.iloc` allows NumPy-like indexing, treating the DataFrame as an array while preserving its index and column labels.

In [29]:
states.iloc[:2, :2]

            population    area
California    39538223  423967
Texas         29145505  695662

In [30]:
states.loc[:'Florida', :'area']

            population    area
California    39538223  423967
Texas         29145505  695662
Florida       21538187  170312

Pandas' `.loc` and `.iloc` indexers support familiar NumPy-style data access patterns, allowing flexible and intuitive data selection. For instance, masking and fancy indexing (selecting multiple non-contiguous indices) can be combined within these indexers.

Additionally, these indexing methods can be used to modify values, just as you would in NumPy.

In [31]:
states.loc[states['population'] > 20_000_000] # .loc with Boolean masking (Select states with population > 20 million)

            population    area     density
California    39538223  423967   93.257784
Texas         29145505  695662   41.896072
Florida       21538187  170312  126.463121
New York      20201249  141297  142.970120

In [32]:
states.loc[['California', 'Texas'], ['population']] # .loc with fancy indexing (Selecting specific states and columns)

            population
California    39538223
Texas         29145505

In [33]:
states.iloc[2, 1] -= 5000  # modify the 'area' value for Florida
states

              population    area     density
California      39538223  423967   93.257784
Texas           29145505  695662   41.896072
Florida         21538187  165312  126.463121
New York        20201249  141297  142.970120
Pennsylvania    13002700  119280  109.009893

In [ ]:
#@title Exercises:

data = {
    "City": ["London", "Birmingham", "Manchester", "Liverpool", "Leeds",
             "Sheffield", "Bristol", "Glasgow", "Edinburgh", "Cardiff"],
    "Population": [8982000, 1141000, 545500, 498000, 789000, 584000, 467000, 633000, 530000, 364000],
    "Area": [1572, 267.8, 115.6, 111.8, 551.7, 367.9, 110, 175.5, 264, 140]
}

# 1: turn data into a pd.DataFrame and create new column with population density

data = pd.DataFrame({
    "City": ["London", "Birmingham", "Manchester", "Liverpool", "Leeds",
             "Sheffield", "Bristol", "Glasgow", "Edinburgh", "Cardiff"],
    "Population": [8982000, 1141000, 545500, 498000, 789000, 584000, 467000, 633000, 530000, 364000],
    "Area": [1572, 267.8, 115.6, 111.8, 551.7, 367.9, 110, 175.5, 264, 140]
})
data['Density'] = data["Population"] / data["Area"]
print(data)

# 2: print the first three rows of the population column

data.iloc[:3, 1]

# 3: print area and density for Liverpool, Bristol, and Cardiff

data.loc[["Liverpool", "Bristol", "Cardiff"], ["Area", "Density"]]

# 4: select and print the rows for cities with a population greater than 500_000.

data.loc[data["Population"] > 500000]

# 5: assume all cities' population has increased by 10%. calculate the new density and save it into a colum

data['New_Density'] = data["Population"] *1.1 / data["Area"]
data

# 6: change Manchester's new density to unknown (use either a np.none or a str instance to fill the new value)

         City  Population    Area      Density
0      London     8982000  1572.0  5713.740458
1  Birmingham     1141000   267.8  4260.642270
2  Manchester      545500   115.6  4718.858131
3   Liverpool      498000   111.8  4454.382826
4       Leeds      789000   551.7  1430.125068
5   Sheffield      584000   367.9  1587.387877
6     Bristol      467000   110.0  4245.454545
7     Glasgow      633000   175.5  3606.837607
8   Edinburgh      530000   264.0  2007.575758
9     Cardiff      364000   140.0  2600.000000

KeyError: "None of [Index(['Liverpool', 'Bristol', 'Cardiff'], dtype='object')] are in the [index]"

## **3**.&nbsp; **Operations on Datasets**

Pandas has several aggregation methods that work simialr to their numpy equivaletns.

| Aggregation Method  | Description                                                | Usage Example                     |
|---------------------|------------------------------------------------------------|-----------------------------------|
| `sum()`             | Computes the sum of values.                                | `df.sum()`                        |
| `mean()`            | Calculates the arithmetic mean.                          | `df.mean()`                       |
| `median()`          | Finds the median (middle) value.                           | `df.median()`                     |
| `min()`             | Retrieves the minimum value.                             | `df.min()`                        |
| `max()`             | Retrieves the maximum value.                             | `df.max()`                        |
| `count()`           | Counts the number of non-null entries.                   | `df.count()`                      |
| `std()`             | Computes the standard deviation.                         | `df.std()`                        |
| `var()`             | Computes the variance.                                   | `df.var()`                        |

### **Vectorised operations**

Pandas inherits element-wise operations from NumPy, allowing efficient arithmetic (e.g., addition, subtraction, multiplication) and more advanced functions (e.g., trigonometric, exponential, logarithmic). However, Pandas enhances these operations with two key features:

1. **Index & Column Preservation**: Unary operations (e.g., negation, trigonometry) retain index and column labels.
2. **Automatic Index Alignment**: Binary operations (e.g., addition, multiplication) align indices when combining different data sources, reducing errors.

In [47]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

print(s1, "\n", s2)

a    1
b    2
c    3
dtype: int64
 b    4
c    5
d    6
dtype: int64

In [48]:
np.exp(s1) # apply np.exp while preserving index

a     2.718282
b     7.389056
c    20.085537
dtype: float64

In [49]:
s1 + s2 # addition with automatic index alignment

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

A similar type of alignment takes place for both columns and indices when performing operations on `DataFrame` objects:

In [50]:
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]}, index=['x', 'y', 'z'])
df

   a  b
x  1  4
y  2  5
z  3  6

In [51]:
df_2 = pd.DataFrame({'b': [1, 2, 3], 'c': [4, 5, 6]}, index=['x', 'y', 'a'])
df_2

   b  c
x  1  4
y  2  5
a  3  6

In [52]:
df + df_2 # idx and columns are aligned

    a    b   c
a NaN  NaN NaN
x NaN  5.0 NaN
y NaN  7.0 NaN
z NaN  NaN NaN

When performing operations between a `DataFrame` and a `Series`, the index and column alignment is similarly maintained, and the result is similar to operations between a two-dimensional and one-dimensional NumPy array.

In [53]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}, index=['x', 'y', 'z'])

df

   A  B  C
x  1  4  7
y  2  5  8
z  3  6  9

In [54]:
df.sum() # specify axis='columns' to change axis of calculation

A     6
B    15
C    24
dtype: int64

### Broadcasting in Pandas

When adding a `Series` to a `DataFrame`, Pandas automatically aligns indices and performs broadcasting. If the `Series` index matches the `DataFrame` columns, it broadcasts row-wise. If the `Series` index matches the `DataFrame` rows, it broadcasts column-wise.

In [149]:
series_col = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
series_col

A    10
B    20
C    30
dtype: int64

In [150]:
result_col = df + series_col
result_col

    A   B   C
x  11  24  37
y  12  25  38
z  13  26  39

In [146]:
series_row = pd.Series([100, 200, 300], index=['x', 'y', 'z'])
series_row

x    100
y    200
z    300
dtype: int64

In [147]:
result_row = df.add(series_row, axis=0)
result_row

# df + series_row #  would not work since Pandas aligns indices based on column labels by default.

     A    B    C
x  101  104  107
y  202  205  208
z  303  306  309

## **4**.&nbsp; **Combining Datasets: Concat, Merge**

### **Concatenating DataFrames with** `pd.concat()`

`pd.concat()` is used for stacking DataFrames vertically (adding rows) or horizontally (adding columns). To work, the DataFrames should have compatible axes (e.g., same columns when stacking rows).

Key parameters:

- `axis`:
    axis=0 (default): Concatenate along rows.
    axis=1: Concatenate along columns.
- `ignore_index`: When `True`, resets the index in the result. By default, pandas preserves indicies, even when it means getting duplicate indicies afer combining data.
- `verify_integrity`: if set to `True`, verifies that the indices in the result of `pd.concat` do not overlap.
- `keys`: specifies the source data, turning the result of `pd.concat` into a hierarchically indexed series containing the data.
- `join`: specifies how to handle missing observarions when joining dataframes with different columns.

In [55]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5']
})

df3 = pd.DataFrame({
    'C': ['C6', 'C7', 'C8'],
    'B': ['B6', 'B7', 'B8']
})

df2

    A   B
0  A3  B3
1  A4  B4
2  A5  B5

In [56]:
vertical_concat = pd.concat([df1, df2],  axis="rows", ignore_index=True) # equivalent to axis=0; verify_integrity=True; ignore_index=True;
vertical_concat

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4
5  A5  B5

In [57]:
horizontal_concat = pd.concat([df1, df2], axis="columns") # equivalent to axis=1
horizontal_concat

    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

In [58]:
concat_with_keys = pd.concat([df1, df2], keys=['df1', 'df2'])
concat_with_keys # hierarchical indexing

        A   B
df1 0  A0  B0
    1  A1  B1
    2  A2  B2
df2 0  A3  B3
    1  A4  B4
    2  A5  B5

In [59]:
concat_with_keys.loc[('df1', 'A')]

0    A0
1    A1
2    A2
Name: A, dtype: object

For a deep dive in hierarchical indexing, refer to [Pandas Data Science Handbook, Ch 17.](https://learning.oreilly.com/library/view/python-data-science/9781098121211/ch17.html)

`pd.concat` also supports combining dataframes with different sets of columns. The default behaviuour is to perform an `join="outer"` - maintain all observations and fill entries for which no data is available with NAs.

In [60]:
pd.concat([df1, df3], ignore_index=True)

     A   B    C
0   A0  B0  NaN
1   A1  B1  NaN
2   A2  B2  NaN
3  NaN  B6   C6
4  NaN  B7   C7
5  NaN  B8   C8

To select only the intersection of colums, specify `join="inner"`

In [61]:
pd.concat([df1, df3], join="inner", ignore_index=True)

    B
0  B0
1  B1
2  B2
3  B6
4  B7
5  B8

### **Merging DataFrames with** `pd.merge()`

`pd.merge()` is used for combining DataFrames based on common columns or indices. Similar to SQL join operations: inner, left, right, and outer joins.


| Join Type  | Keeps Non-Matching Rows? | Fills `NaN`? | Best Use Case |
|------------|-------------------------|-------------|---------------|
| **Inner**  | ❌ No  | ❌ No  | Matching records only |
| **Left**   | ✅ Yes (from left)  | ✅ Yes (if no match in right) | Preserve all data from **left** |
| **Right**  | ✅ Yes (from right)  | ✅ Yes (if no match in left) | Preserve all data from **right** |
| **Outer**  | ✅ Yes (from both)  | ✅ Yes | Keep all records from **both sides** |


`pd.merge()` further supports joins by relationship types, namely *one-to-one, many-to-one, and many-to-many*.

- **one-to-one**: is in many ways similar to the column-wise concatenation with pd.concat - each key in the left DataFrame matches at most one row in the right DataFrame.

- **many-to-one**: a unique key is matched to duplicate entities.

- **many-to-many**: if the key column in both the left and right arrays contains duplicates, then every row from the left DataFrame that has a matching key is combined with every row from the right DataFrame that shares that key.


Key parameters:

- `on`: Key Column name(s) common to both DataFrames.
- `left_on` / `right_on`: Specify different columns to join on.  
- `how`:

    `'inner'` (default): Only matching rows.

    `'left'`: All rows from the left DataFrame.

    `'right'`: All rows from the right DataFrame.

    `'outer'`: All rows from both DataFrames.

In [182]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue', 'Ed'],
                    'group': ['Accounting', 'Engineering',
                                'Engineering', 'HR', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

df3 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

df4 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                            'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'software', 'math',
                                'spreadsheets', 'organization']})

df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4       Ed           HR

In [192]:
merged = pd.merge(df1, df2, on='employee', how='left') # one-to-one
merged

  employee        group  hire_date
0      Bob   Accounting     2008.0
1     Jake  Engineering     2012.0
2     Lisa  Engineering     2004.0
3      Sue           HR     2014.0
4       Ed           HR        NaN

In [191]:
df3

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [193]:
pd.merge(merged, df3) # many-to-one join

  employee        group  hire_date supervisor
0      Bob   Accounting     2008.0      Carly
1     Jake  Engineering     2012.0      Guido
2     Lisa  Engineering     2004.0      Guido
3      Sue           HR     2014.0      Steve
4       Ed           HR        NaN      Steve

In [194]:
df4

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering      software
3  Engineering          math
4           HR  spreadsheets
5           HR  organization

In [195]:
pd.merge(merged, df4) # many-to-many join

  employee        group  hire_date        skills
0      Bob   Accounting     2008.0          math
1      Bob   Accounting     2008.0  spreadsheets
2     Jake  Engineering     2012.0      software
3     Jake  Engineering     2012.0          math
4     Lisa  Engineering     2004.0      software
5     Lisa  Engineering     2004.0          math
6      Sue           HR     2014.0  spreadsheets
7      Sue           HR     2014.0  organization
8       Ed           HR        NaN  spreadsheets
9       Ed           HR        NaN  organization

In [198]:
df5 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue', 'Ed'],
                            'salary': [70000, 80000, 120000, 90000, 65000]})
df5

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000
4    Ed   65000

In [199]:
pd.merge(merged, df5, left_on="employee", right_on="name") # use df.drop method to remove redundant cols

  employee        group  hire_date  name  salary
0      Bob   Accounting     2008.0   Bob   70000
1     Jake  Engineering     2012.0  Jake   80000
2     Lisa  Engineering     2004.0  Lisa  120000
3      Sue           HR     2014.0   Sue   90000
4       Ed           HR        NaN    Ed   65000

In [ ]:
#@title Exercises

election_results1 = pd.DataFrame({
    'CandidateID': ['C001', 'C002', 'C003'],
    'Votes': [3500, 4200, 2900],
    'Region': ['North', 'South', 'East']
})

election_results2 = pd.DataFrame({
    'CandidateID': ['C004', 'C005', 'C006'],
    'Votes': [3100, 5000, 4300],
    'Region': ['West', 'North', 'South']
})

candidate_info = pd.DataFrame({
    'CandidateID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006'],
    'CandidateName': ['Alice Smith', 'Bob Johnson', 'Carol White', 'Dave Lee', 'Evelina Wolf', 'Frank Miller'],
    'Party': ['Party A', 'Party B', 'Party A', 'Party C', 'Party B', 'Party C']
})

region_info = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West'],
    'Industry': ['Car Manufacturing', 'Finance', 'Tech', 'Agriculture']
})

fundraising = pd.DataFrame({
    'CandidateID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006'],
    'FundsRaised': [500_000, 60_000, 45_000, 55_000, 7000_000, 65_000]
})


# 1: combine election results

df = pd.merge(election_results1, election_results2, how="outer")

# 2: extend the resulting df from task one to contain candidate names and party affiliation

df = pd.merge(df, region_info, how="left")

# 3: merge the df from task 2 with fundraising details and regional industry specialisation

df = pd.merge(df, region_info, how="left")
df = pd.merge(df, fundraising, how="")

# 4: create a new column "FundsPerVote" calculating the amount of fundrising it took to win each vote

df['FundsPerVote'] = df['FundsRaised'] / df['Votes']
df

# 5: find total funds per vote raised by each party

df.groupby("Party")["FundsPerVote"].sum()

## **5**.&nbsp; **Loading, Exploring, and Saving Data**

In [216]:
!git clone https://github.com/antndlcrx/Intro-to-Python-DPIR.git

Cloning into 'Intro-to-Python-DPIR'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 67 (delta 19), reused 36 (delta 5), pack-reused 0 (from 0)
Receiving objects: 100% (67/67), 803.51 KiB | 3.40 MiB/s, done.
Resolving deltas: 100% (19/19), done.

For this section, we will work on the **Quality of Government dataset**: a collection of social,
 political and economic indicators for all the countries of the world. The dataset is maintained by a team of
 researchers at the University of Gothenburg. You can learn more about the project, download more data
 etc. at the [Quality of Government institute website](https://www.gu.se/en/quality-government). The file qog2022.csv, is a cleaned-up and trimmed-down version of the "QOG Basic
 Dataset 2022".

The example dataset has the following variables:

| Variable      | Description |
|--------------|-------------|
| **country**  | Country name |
| **iso3c**    | Country code (isocode-3) |
| **region**   | UN Region (continent) |
| **fh_status** | Freedom House Rating (Free, Partly Free, Not Free) |
| **perc_wip** | Proportion of women in parliament (World Development Indicators) |
| **hdi**      | Human Development Index (UN Development Programme) |
| **glob_index** | Index of Globalisation (1-100 scale: higher = more globalised) |
| **fh_polity**  | Freedom House Polity Score (0-10 scale: higher = more democratic) |
| **gdp_pc**     | Real GDP per capita (Maddison Project) |
| **corruption** | V-Dem corruption index (higher = more corrupt) |

In [342]:
qog_link = '/content/Intro-to-Python-DPIR/datasets/qog2022.csv'
qog = pd.read_csv(qog_link) # function to read in data from .csv file

# df = pd.read_json() # function to read in data from .csv file
# df = pd.read_parquet() # function to read in data from .csv file

In [343]:
# pd.set_option("display.max_columns", 10) # run this to show more columns
qog.head() # display first n observations

,country,region,iso3c,perc_wip,gdp_pc,corruption,hdi,glob_index,fh_polity,fh_status
0,Afghanistan,Asia,AFG,27.868853,1934.555054,0.908,0.509,38.519566,3.500000,Not Free
1,Albania,Europe,ALB,27.857143,11104.166016,0.796,0.792,66.650490,8.083333,Partly Free
2,Algeria,Africa,DZA,25.757576,14228.025391,0.714,0.746,56.150364,4.250000,Not Free
3,Andorra,Europe,AND,32.142857,NaN,NaN,0.867,50.380840,10.000000,Free
4,Angola,Africa,AGO,30.454546,7771.441895,0.629,0.582,42.808849,3.250000,Not Free

In [272]:
# print all columns
qog.columns
# print all index values
# qog.index

Index(['country', 'region', 'iso3c', 'perc_wip', 'gdp_pc', 'corruption', 'hdi',
       'glob_index', 'fh_polity', 'fh_status'],
      dtype='object')

In [225]:
# qog.info() # get info on your dataset
# # qog.info(verbose=False)

In [226]:
# qog.describe() # descriptive stats in the data

In [230]:
# qog['fh_status'].value_counts() # normalize=True for shares

In [234]:
# qog['country'].unique() # nunique()

In [ ]:
# df.to_csv("df.csv", index=False) # writes a dataframe object into a .csv file

## **6**.&nbsp; **Grouping**


A very useful feature in pandas is the `groupby` method that allows to aggregate *conditionally* on some label or index.

`groupby` works following the **split-apply-combine** sequence.

- *split:* break up and group data based on the grouping key.
- *apply:* apply some function (usually and aggregate, transformation, or filtering) within the groups.
- *combine:* merge the results of these operations.


<img src="https://cdn.githubraw.com/antndlcrx/Intro-to-Python-DPIR/main/images/W3/groupby.png?raw=true:,  width=150" alt="My Image" width=475>

[Img source: Pandas Data Science Handbook, Ch 20.](https://learning.oreilly.com/library/view/python-data-science/9781098121211/ch20.html)

In [247]:
qog.groupby(['region', 'fh_status'])['gdp_pc'].std()

region    fh_status
Africa    Free            6034.243944
          Not Free        7441.996186
          Partly Free     6041.507560
Americas  Free           13742.126461
          Not Free        2892.854482
          Partly Free     5000.796315
Asia      Free           13986.611698
          Not Free       34184.129141
          Partly Free    20807.222187
Europe    Free           14998.730004
          Not Free        4201.338470
          Partly Free     6059.341668
Oceania   Free           10249.275250
          Partly Free             NaN
Name: gdp_pc, dtype: float64

In [235]:
qog.groupby('region')[['gdp_pc', 'fh_polity']].mean()

                gdp_pc  fh_polity
region
Africa     5877.427981   5.232351
Americas  15237.620759   8.220772
Asia      22912.591952   4.406302
Europe    32093.471730   8.923796
Oceania   42583.468750   9.001371

In [ ]:
qog.groupby(['fh_status', 'region'])

In [ ]:
qog.groupby(['fh_status', 'region'])[['gdp_pc', 'fh_polity']].describe()

                     gdp_pc                                            \
                      count          mean           std           min
fh_status   region
Free        Africa     10.0   8820.929224   6034.243944   2220.176514
            Americas   15.0  20041.988932  13742.126461   7272.980469
            Asia        7.0  28799.072475  13986.611698   6806.498535
            Europe     29.0  37855.140423  14998.730004  18444.259766
            Oceania     2.0  42583.468750  10249.275250  35336.136719
Not Free    Africa     19.0   6942.627975   7441.996186    623.488892
            Americas    3.0   7996.019368   2892.854482   4952.477051
            Asia       22.0  24785.654741  34184.129141   1596.351685
            Europe      2.0  21698.113281   4201.338470  18727.318359
Partly Free Africa     22.0   3619.527421   6041.507560    818.421082
            Americas    9.0   9644.207601   5000.796315   1729.043213
            Asia       15.0  17418.408952  20807.222187   2727.423828
            Europe      8.0  13806.262329   6059.341668   6746.728516
            Oceania     0.0           NaN           NaN           NaN

                                                                               \
                               25%           50%           75%            max
fh_status   region
Free        Africa     3864.420166   7937.167969  11962.817871   20138.572266
            Americas  11235.277832  14686.253906  22370.957031   55334.738281
            Asia      20283.479004  32954.769531  38300.708984   44663.863281
            Europe    27370.554688  34364.167969  45541.890625   84580.132812
            Oceania   38959.802734  42583.468750  46207.134766   49830.800781
Not Free    Africa     1987.352722   3379.595703  10012.711914   28528.953125
            Americas   6639.053955   8325.630859   9517.790527   10709.950195
            Asia       4943.013062  14864.880371  26065.662598  153764.171875
            Europe    20212.715820  21698.113281  23183.510742   24668.908203
Partly Free Africa     1463.874023   1675.572388   3251.843567   29531.060547
            Americas   6695.774414   9338.948242  13545.049805   16494.078125
            Asia       5674.306885  11506.337891  12271.936035   68402.343750
            Europe    10298.731201  12089.198730  15469.128174   25622.812500
            Oceania            NaN           NaN           NaN            NaN

                     fh_polity                                          \
                         count      mean       std       min       25%
fh_status   region
Free        Africa        10.0  8.658813  0.732196  7.750000  8.062500
            Americas      23.0  9.292479  0.764553  7.500000  8.791666
            Asia           8.0  9.093750  0.906806  7.750000  8.437500
            Europe        33.0  9.686173  0.428163  8.588133  9.500000
            Oceania       12.0  9.418266  0.719235  8.588133  8.588133
Not Free    Africa        22.0  2.742424  1.101319  0.666667  2.333333
            Americas       3.0  3.027778  1.940671  1.666667  1.916667
            Asia          23.0  1.697925  1.273605  0.000000  0.791667
            Europe         2.0  2.541667  1.944544  1.166667  1.854167
Partly Free Africa        22.0  6.164796  1.214490  3.166666  5.583333
            Americas       9.0  7.212963  0.795071  5.416666  7.000000
            Asia          17.0  5.864720  1.822267  2.416666  4.500000
            Europe         8.0  7.374526  0.999122  5.329542  7.354167
            Oceania        2.0  6.500000  0.235703  6.333333  6.416666


                            50%        75%        max
fh_status   region
Free        Africa     8.502399   9.041667  10.000000
            Americas   9.402781  10.000000  10.000000
            Asia       9.125000  10.000000  10.000000
            Europe    10.000000  10.000000  10.000000
            Oceania   10.000000  10.000000  10.000000
Not Free    Africa     2.625000   3.562500   4.500000
            Americas   2.166667   3.708333   5.250000
            Asia       1.583333   2.666667   5.250000
            Europe     2.541667   3.229167   3.916667
Partly Free Africa     6.250000   6.948295   7.833333
            Americas   7.583333   7.583333   8.083333
            Asia       6.583333   7.166667   8.083333
            Europe     7.666667   7.895833   8.333333
            Oceania    6.500000   6.583334   6.666667

You can apply multiple functions at once using `.agg()`

In [266]:
grouped = qog.groupby(['fh_status', 'region'])['gdp_pc'].agg(['mean', 'std'])
grouped

                              mean           std
fh_status   region
Free        Africa     8820.929224   6034.243944
            Americas  20041.988932  13742.126461
            Asia      28799.072475  13986.611698
            Europe    37855.140423  14998.730004
            Oceania   42583.468750  10249.275250
Not Free    Africa     6942.627975   7441.996186
            Americas   7996.019368   2892.854482
            Asia      24785.654741  34184.129141
            Europe    21698.113281   4201.338470
Partly Free Africa     3619.527421   6041.507560
            Americas   9644.207601   5000.796315
            Asia      17418.408952  20807.222187
            Europe    13806.262329   6059.341668
            Oceania            NaN           NaN

By default, `groupby()` creates a hierarchical index. You can convert it back to a regular DataFrame using `.reset_index()`.

In [253]:
grouped.reset_index()

      fh_status    region          mean           std
0          Free    Africa   8820.929224   6034.243944
1          Free  Americas  20041.988932  13742.126461
2          Free      Asia  28799.072475  13986.611698
3          Free    Europe  37855.140423  14998.730004
4          Free   Oceania  42583.468750  10249.275250
5      Not Free    Africa   6942.627975   7441.996186
6      Not Free  Americas   7996.019368   2892.854482
7      Not Free      Asia  24785.654741  34184.129141
8      Not Free    Europe  21698.113281   4201.338470
9   Partly Free    Africa   3619.527421   6041.507560
10  Partly Free  Americas   9644.207601   5000.796315
11  Partly Free      Asia  17418.408952  20807.222187
12  Partly Free    Europe  13806.262329   6059.341668
13  Partly Free   Oceania           NaN           NaN

You can use `.apply()` to perform custom functions on each group. You can define a custom function either via the `def` or `lambda` keywords.



```
lambda arguments: expression
```

`lambda` can have any number of arguments, but it must have only one expression.

In [271]:
qog.groupby('region')['gdp_pc'].apply(lambda x: x.max() - x.min()) # difference between highest and lowest gdp

region
Africa       28907.571655
Americas     53605.695068
Asia        152167.820190
Europe       77833.404297
Oceania      14494.664062
Name: gdp_pc, dtype: float64

Use `filter()` to remove groups that do not meet a condition. The result keeps individual rows from qualifying groups.

In [262]:
qog.groupby('region')['gdp_pc'].filter(lambda x: x.mean() > 10000)

0       1934.555054
1      11104.166016
3               NaN
5               NaN
6      16628.054688
           ...
188    20185.835938
189    11220.370117
190    10709.950195
191             NaN
192     2284.889893
Name: gdp_pc, Length: 140, dtype: float64

### Summary of some grouping comands

| Task | Code |
|------|------|
| Sum each group | `df.groupby("column")["value"].sum()` |
| Mean of each group | `df.groupby("column")["value"].mean()` |
| Multiple aggregations | `df.groupby("column")["value"].agg(["sum", "count", "mean"])` |
| Group by multiple columns | `df.groupby(["col1", "col2"])["value"].sum()` |
| Reset index | `.reset_index()` |
| Apply custom function | `.apply(lambda x: x.func())` |
| Filter groups | `.filter(lambda x: condition)` |

### Exercises

For the excersises, you will also use the the **Parliamentary Power Index**, an indicator of the extent of the formal powers of a legislature, computed by [Steven Fish and Matthew Kroenig](https://assets.cambridge.org/97805215/14668/frontmatter/9780521514668_frontmatter.pdf).

In [283]:
ppi_link = "/content/Intro-to-Python-DPIR/datasets/ppi.csv"

In [ ]:
# 1: read the ppi dataset containing the ppi index

# 2: merge qog and ppi; make sure you i) maintain all qog observations and ii) there are no redundant columns

# 3: calculate average ppi across different regime types (by fh status)

# 4: calculate average corruption and the variation in corruption across countries with ppi larger than 0.4

# 5: do the same but only for africa and asia

# 6: for every region, find the average proportion of women in parliament in countries above their regional parliamentary power index average

# 7: how many countries per region have a human development index higher than the global average?

## Extra I: Missing Data

Pandas operates with multiple missing data types `None`, `NaN`, and `NA`. Pandas treats them interchangebly.

For detecting, removing, and replacing missing data, use methods:

- `isnull`: creates a boolean mask indicating missing values.
- `notnull`: the opposite of `isnull`.
- `dropna`: returns a filtered version of the data.
- `fillna`: returns a copy of the data with missings filled or imputed

In [2]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [3]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [4]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [5]:
data.dropna()

0        1
2    hello
dtype: object

In [6]:
df = pd.DataFrame([[1,      np.nan, 2],
                    [2,      3,      5],
                    [np.nan, 4,      6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [7]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [8]:
df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [9]:
df.fillna(0)

     0    1  2
0  1.0  0.0  2
1  2.0  3.0  5
2  0.0  4.0  6